// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package implementation_2_onegenericevent.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the Implementation_2_OneGenericEvent module
	public static java.util.List<implementation_2_onegenericevent.proxies.GatePLC> dS_GetGate(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("Implementation_2_OneGenericEvent.DS_GetGate").withParams(params).execute(context);
		if (objs == null) {
			return null;
		} else {
			return objs.stream()
				.map(obj -> implementation_2_onegenericevent.proxies.GatePLC.initialize(context, obj))
				.collect(java.util.stream.Collectors.toList());
		}
	}
	public static void mB_CloseGate(IContext context, implementation_2_onegenericevent.proxies.GatePLC _gatePLC)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GatePLC", _gatePLC == null ? null : _gatePLC.getMendixObject());
		Core.microflowCall("Implementation_2_OneGenericEvent.MB_CloseGate").withParams(params).execute(context);
	}
	public static void mB_OpenGate(IContext context, implementation_2_onegenericevent.proxies.GatePLC _gatePLC)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GatePLC", _gatePLC == null ? null : _gatePLC.getMendixObject());
		Core.microflowCall("Implementation_2_OneGenericEvent.MB_OpenGate").withParams(params).execute(context);
	}
	public static void mB_ResetSubscriptions(IContext context, implementation_2_onegenericevent.proxies.GatePLC _gatePLC)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GatePLC", _gatePLC == null ? null : _gatePLC.getMendixObject());
		Core.microflowCall("Implementation_2_OneGenericEvent.MB_ResetSubscriptions").withParams(params).execute(context);
	}
	public static void mB_SetupSubscriptions(IContext context, implementation_2_onegenericevent.proxies.GatePLC _gatePLC)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GatePLC", _gatePLC == null ? null : _gatePLC.getMendixObject());
		Core.microflowCall("Implementation_2_OneGenericEvent.MB_SetupSubscriptions").withParams(params).execute(context);
	}
	public static void nav_OpenDashboard(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Implementation_2_OneGenericEvent.Nav_OpenDashboard").withParams(params).execute(context);
	}
	public static void uA_ProcessGateEvent(IContext context, opcuaclientmx.proxies.Message _message)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Message", _message == null ? null : _message.getMendixObject());
		Core.microflowCall("Implementation_2_OneGenericEvent.UA_ProcessGateEvent").withParams(params).execute(context);
	}
}
