// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package opcuaclient_exampleimplementation.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the OpcUaClient_ExampleImplementation module
	public static java.util.List<opcuaclient_exampleimplementation.proxies.GatePLC> dS_GetGate(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("OpcUaClient_ExampleImplementation.DS_GetGate").withParams(params).execute(context);
		java.util.List<opcuaclient_exampleimplementation.proxies.GatePLC> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(opcuaclient_exampleimplementation.proxies.GatePLC.initialize(context, obj));
		}
		return result;
	}
	public static opcuaclient_exampleimplementation.proxies.Set getOpcUaNodeSet(IContext context, opcuaclientmx.proxies.OpcUaServerCfg _opcUaServerCfg)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("OpcUaServerCfg", _opcUaServerCfg == null ? null : _opcUaServerCfg.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("OpcUaClient_ExampleImplementation.GetOpcUaNodeSet").withParams(params).execute(context);
		return result == null ? null : opcuaclient_exampleimplementation.proxies.Set.initialize(context, result);
	}
	public static opcuaclient_exampleimplementation.proxies.Set getSet(IContext context, opcuaclientmx.proxies.OpcUaServerCfg _opcUaServerCfg)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("OpcUaServerCfg", _opcUaServerCfg == null ? null : _opcUaServerCfg.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("OpcUaClient_ExampleImplementation.GetSet").withParams(params).execute(context);
		return result == null ? null : opcuaclient_exampleimplementation.proxies.Set.initialize(context, result);
	}
	public static void mB_CloseGate(IContext context, opcuaclient_exampleimplementation.proxies.GatePLC _gatePLC)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GatePLC", _gatePLC == null ? null : _gatePLC.getMendixObject());
		Core.microflowCall("OpcUaClient_ExampleImplementation.MB_CloseGate").withParams(params).execute(context);
	}
	public static void mB_OpenGate(IContext context, opcuaclient_exampleimplementation.proxies.GatePLC _gatePLC)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GatePLC", _gatePLC == null ? null : _gatePLC.getMendixObject());
		Core.microflowCall("OpcUaClient_ExampleImplementation.MB_OpenGate").withParams(params).execute(context);
	}
	public static void mB_ResetSubscriptions(IContext context, opcuaclient_exampleimplementation.proxies.GatePLC _gatePLC)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GatePLC", _gatePLC == null ? null : _gatePLC.getMendixObject());
		Core.microflowCall("OpcUaClient_ExampleImplementation.MB_ResetSubscriptions").withParams(params).execute(context);
	}
	public static void mB_SetupSubscriptions(IContext context, opcuaclient_exampleimplementation.proxies.GatePLC _gatePLC)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("GatePLC", _gatePLC == null ? null : _gatePLC.getMendixObject());
		Core.microflowCall("OpcUaClient_ExampleImplementation.MB_SetupSubscriptions").withParams(params).execute(context);
	}
	public static void monitoredItem_Create(IContext context, java.lang.String _payload, java.lang.String _subscriptionID)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Payload", _payload);
		params.put("SubscriptionID", _subscriptionID);
		Core.microflowCall("OpcUaClient_ExampleImplementation.MonitoredItem_Create").withParams(params).execute(context);
	}
	public static void monitoredItem_Delete(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("OpcUaClient_ExampleImplementation.MonitoredItem_Delete").withParams(params).execute(context);
	}
	public static void nav_OpenDashboard(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("OpcUaClient_ExampleImplementation.Nav_OpenDashboard").withParams(params).execute(context);
	}
	public static java.util.List<opcuaclient_exampleimplementation.proxies.OpcUaNode> opcUaNode_Browse_FromNode(IContext context, opcuaclient_exampleimplementation.proxies.OpcUaNode _opcUaNode)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("OpcUaNode", _opcUaNode == null ? null : _opcUaNode.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("OpcUaClient_ExampleImplementation.OpcUaNode_Browse_FromNode").withParams(params).execute(context);
		java.util.List<opcuaclient_exampleimplementation.proxies.OpcUaNode> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(opcuaclient_exampleimplementation.proxies.OpcUaNode.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<opcuaclient_exampleimplementation.proxies.OpcUaNode> opcUaNode_Browse_FromSet(IContext context, opcuaclient_exampleimplementation.proxies.OpcUaNode _opcUaNode)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("OpcUaNode", _opcUaNode == null ? null : _opcUaNode.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("OpcUaClient_ExampleImplementation.OpcUaNode_Browse_FromSet").withParams(params).execute(context);
		java.util.List<opcuaclient_exampleimplementation.proxies.OpcUaNode> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(opcuaclient_exampleimplementation.proxies.OpcUaNode.initialize(context, obj));
		}
		return result;
	}
	public static void opcUaNode_Browse_TopLevel(IContext context, opcuaclientmx.proxies.OpcUaServerCfg _opcUaServer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("OpcUaServer", _opcUaServer == null ? null : _opcUaServer.getMendixObject());
		Core.microflowCall("OpcUaClient_ExampleImplementation.OpcUaNode_Browse_TopLevel").withParams(params).execute(context);
	}
	public static opcuaclient_exampleimplementation.proxies.OpcUaNode opcUaNode_Create(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("OpcUaClient_ExampleImplementation.OpcUaNode_Create").withParams(params).execute(context);
		return result == null ? null : opcuaclient_exampleimplementation.proxies.OpcUaNode.initialize(context, result);
	}
	public static void opcUaNode_DeleteAll(IContext context, opcuaclientmx.proxies.OpcUaServerCfg _opcUaServerCfg)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("OpcUaServerCfg", _opcUaServerCfg == null ? null : _opcUaServerCfg.getMendixObject());
		Core.microflowCall("OpcUaClient_ExampleImplementation.OpcUaNode_DeleteAll").withParams(params).execute(context);
	}
	public static java.util.List<opcuaclient_exampleimplementation.proxies.OpcUaNode> opcUaNode_GetForNodeView(IContext context, opcuaclientmx.proxies.OpcUaServerCfg _opcUaServerCfg)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("OpcUaServerCfg", _opcUaServerCfg == null ? null : _opcUaServerCfg.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("OpcUaClient_ExampleImplementation.OpcUaNode_GetForNodeView").withParams(params).execute(context);
		java.util.List<opcuaclient_exampleimplementation.proxies.OpcUaNode> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(opcuaclient_exampleimplementation.proxies.OpcUaNode.initialize(context, obj));
		}
		return result;
	}
	public static void opcUaNode_Read(IContext context, opcuaclient_exampleimplementation.proxies.OpcUaNode _opcUaNode)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("OpcUaNode", _opcUaNode == null ? null : _opcUaNode.getMendixObject());
		Core.microflowCall("OpcUaClient_ExampleImplementation.OpcUaNode_Read").withParams(params).execute(context);
	}
	public static void opcUaNode_Subscribe(IContext context, opcuaclient_exampleimplementation.proxies.OpcUaNode _opcUaNode)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("OpcUaNode", _opcUaNode == null ? null : _opcUaNode.getMendixObject());
		Core.microflowCall("OpcUaClient_ExampleImplementation.OpcUaNode_Subscribe").withParams(params).execute(context);
	}
	public static void opcUaNode_Write(IContext context, opcuaclient_exampleimplementation.proxies.OpcUaNode _opcUaNode)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("OpcUaNode", _opcUaNode == null ? null : _opcUaNode.getMendixObject());
		Core.microflowCall("OpcUaClient_ExampleImplementation.OpcUaNode_Write").withParams(params).execute(context);
	}
	public static void processOpcUaNode(IContext context, opcuaclient_exampleimplementation.proxies.OpcUaNode _mappingParent, opcuaclient_exampleimplementation.proxies.OpcUaNode _parentOpcUaNode, opcuaclientmx.proxies.OpcUaServerCfg _opcUaServerCfg)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("MappingParent", _mappingParent == null ? null : _mappingParent.getMendixObject());
		params.put("ParentOpcUaNode", _parentOpcUaNode == null ? null : _parentOpcUaNode.getMendixObject());
		params.put("OpcUaServerCfg", _opcUaServerCfg == null ? null : _opcUaServerCfg.getMendixObject());
		Core.microflowCall("OpcUaClient_ExampleImplementation.ProcessOpcUaNode").withParams(params).execute(context);
	}
	public static java.util.List<opcuaclient_exampleimplementation.proxies.OpcUaNode> processOpcUaNodeList(IContext context, java.lang.String _result, opcuaclient_exampleimplementation.proxies.OpcUaNode _parentOpcUaNode, opcuaclientmx.proxies.OpcUaServerCfg _opcUaServer)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Result", _result);
		params.put("ParentOpcUaNode", _parentOpcUaNode == null ? null : _parentOpcUaNode.getMendixObject());
		params.put("OpcUaServer", _opcUaServer == null ? null : _opcUaServer.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("OpcUaClient_ExampleImplementation.ProcessOpcUaNodeList").withParams(params).execute(context);
		java.util.List<opcuaclient_exampleimplementation.proxies.OpcUaNode> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(opcuaclient_exampleimplementation.proxies.OpcUaNode.initialize(context, obj));
		}
		return result;
	}
	public static void uA_ProcessEvent_GateDown(IContext context, opcuaclientmx.proxies.Message _message)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Message", _message == null ? null : _message.getMendixObject());
		Core.microflowCall("OpcUaClient_ExampleImplementation.UA_ProcessEvent_GateDown").withParams(params).execute(context);
	}
	public static void uA_ProcessEvent_GateMoving(IContext context, opcuaclientmx.proxies.Message _message)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Message", _message == null ? null : _message.getMendixObject());
		Core.microflowCall("OpcUaClient_ExampleImplementation.UA_ProcessEvent_GateMoving").withParams(params).execute(context);
	}
	public static void uA_ProcessEvent_GateUp(IContext context, opcuaclientmx.proxies.Message _message)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Message", _message == null ? null : _message.getMendixObject());
		Core.microflowCall("OpcUaClient_ExampleImplementation.UA_ProcessEvent_GateUp").withParams(params).execute(context);
	}
}