// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package opcuaclientmx.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the OpcUaClientMx module

	/**
	* This is the friendly name under which this application will register itself at the server. There are no requirements from Mendix on this field.
	* 
	* Suggestions are:
	* - Use a unique name (such as your actual application name)
	* - Avoid special characters (- or _ should not be an issue)
	*/
	public static java.lang.String getUA_ApplicationName()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("OpcUaClientMx.UA_ApplicationName");
	}

	/**
	* This constant must be in a URI format. It's recommended to only change the last element to identify your application. 
	* e.g. Leave: "urn:siemens:mendix:" as is, and add your chosen application identifier.
	* 
	* If you are using client certificates for authentication, the URI should match the certificate. Other than that there are no requirements on what this must be this is only for identification of your app in your server, This must be unique across all Clients served by your OPC UA Server.
	*/
	public static java.lang.String getUA_ApplicationURI()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("OpcUaClientMx.UA_ApplicationURI");
	}

	/**
	* NOT IMPLEMENTED YET.   Once implemented you can specify a JSON string to feed the advanced parameters of the OPC UA Client configuration.
	* 
	* When leaving blank the default values from the Apache Milo module will be used.
	* 
	* JSON Client configuration.
	* {
	* "appname":"MyAppName",
	* "app_uri":"".
	* "RequestTimeout":5000,
	* "SessionTimeout":60000,
	* "KeepAliveTimeout":5000
	* }
	*/
	public static java.lang.String getUA_xAdvancedClientSettings()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("OpcUaClientMx.UA_xAdvancedClientSettings");
	}
}