// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package opcuaclientmx.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import opcuaclientmx.impl.SubscriptionManager;

public class OpcUaSubscribe extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __OpcUaServerCfg;
	private opcuaclientmx.proxies.OpcUaServerCfg OpcUaServerCfg;
	private java.lang.String nodeId;
	private java.lang.String OnMessageMicroflow;
	private IMendixObject __Subscription;
	private opcuaclientmx.proxies.Subscription Subscription;

	public OpcUaSubscribe(IContext context, IMendixObject OpcUaServerCfg, java.lang.String nodeId, java.lang.String OnMessageMicroflow, IMendixObject Subscription)
	{
		super(context);
		this.__OpcUaServerCfg = OpcUaServerCfg;
		this.nodeId = nodeId;
		this.OnMessageMicroflow = OnMessageMicroflow;
		this.__Subscription = Subscription;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.OpcUaServerCfg = this.__OpcUaServerCfg == null ? null : opcuaclientmx.proxies.OpcUaServerCfg.initialize(getContext(), __OpcUaServerCfg);

		this.Subscription = this.__Subscription == null ? null : opcuaclientmx.proxies.Subscription.initialize(getContext(), __Subscription);

		// BEGIN USER CODE
		return SubscriptionManager._getInstance().addSubscription(getContext(), this.OpcUaServerCfg, this.Subscription, this.nodeId, this.OnMessageMicroflow);
	
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "OpcUaSubscribe";
	}

	// BEGIN EXTRA CODE
	


	// END EXTRA CODE
}
