// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package opcuaclientmx.actions;

import org.eclipse.milo.opcua.sdk.client.OpcUaClient;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import opcuaclientmx.impl.OpcUaClientManager;

public class OpcUaConnectionTest extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __OpcUaServerCfg;
	private opcuaclientmx.proxies.OpcUaServerCfg OpcUaServerCfg;

	public OpcUaConnectionTest(IContext context, IMendixObject OpcUaServerCfg)
	{
		super(context);
		this.__OpcUaServerCfg = OpcUaServerCfg;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.OpcUaServerCfg = __OpcUaServerCfg == null ? null : opcuaclientmx.proxies.OpcUaServerCfg.initialize(getContext(), __OpcUaServerCfg);

		// BEGIN USER CODE
		
		OpcUaClient client = OpcUaClientManager.retrieve(context(), this.OpcUaServerCfg);
		
		client.disconnect().get(); //Disconnect since we don't want to keep the connection
		
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "OpcUaConnectionTest";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
