// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package opcuaclientmx.actions;

import org.eclipse.milo.opcua.stack.core.types.builtin.NodeId;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class OpcUaBuildNodeId extends CustomJavaAction<java.lang.String>
{
	private java.lang.Long Namespace;
	private java.lang.String Identifier;
	private java.lang.String _type;

	public OpcUaBuildNodeId(IContext context, java.lang.Long Namespace, java.lang.String Identifier, java.lang.String _type)
	{
		super(context);
		this.Namespace = Namespace;
		this.Identifier = Identifier;
		this._type = _type;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		if( "Numeric".equalsIgnoreCase(this._type) ) {
			return (new NodeId(this.Namespace.intValue(), Integer.valueOf(this.Identifier))).toParseableString();
		}
		
		return (new NodeId(this.Namespace.intValue(), this.Identifier)).toParseableString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "OpcUaBuildNodeId";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
