// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package opcuaclientmx.proxies;

public class Message
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject messageMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OpcUaClientMx.Message";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ServerID("ServerID"),
		SubscriptionID("SubscriptionID"),
		MonitoredItemID("MonitoredItemID"),
		Payload("Payload"),
		StatusCodeName("StatusCodeName"),
		SourceTime("SourceTime"),
		ServerTime("ServerTime"),
		FullMessage("FullMessage");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Message(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "OpcUaClientMx.Message"));
	}

	protected Message(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject messageMendixObject)
	{
		if (messageMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("OpcUaClientMx.Message", messageMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a OpcUaClientMx.Message");

		this.messageMendixObject = messageMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Message.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static opcuaclientmx.proxies.Message initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return opcuaclientmx.proxies.Message.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static opcuaclientmx.proxies.Message initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new opcuaclientmx.proxies.Message(context, mendixObject);
	}

	public static opcuaclientmx.proxies.Message load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return opcuaclientmx.proxies.Message.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ServerID
	 */
	public final java.lang.String getServerID()
	{
		return getServerID(getContext());
	}

	/**
	 * @param context
	 * @return value of ServerID
	 */
	public final java.lang.String getServerID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ServerID.toString());
	}

	/**
	 * Set value of ServerID
	 * @param serverid
	 */
	public final void setServerID(java.lang.String serverid)
	{
		setServerID(getContext(), serverid);
	}

	/**
	 * Set value of ServerID
	 * @param context
	 * @param serverid
	 */
	public final void setServerID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String serverid)
	{
		getMendixObject().setValue(context, MemberNames.ServerID.toString(), serverid);
	}

	/**
	 * @return value of SubscriptionID
	 */
	public final java.lang.String getSubscriptionID()
	{
		return getSubscriptionID(getContext());
	}

	/**
	 * @param context
	 * @return value of SubscriptionID
	 */
	public final java.lang.String getSubscriptionID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SubscriptionID.toString());
	}

	/**
	 * Set value of SubscriptionID
	 * @param subscriptionid
	 */
	public final void setSubscriptionID(java.lang.String subscriptionid)
	{
		setSubscriptionID(getContext(), subscriptionid);
	}

	/**
	 * Set value of SubscriptionID
	 * @param context
	 * @param subscriptionid
	 */
	public final void setSubscriptionID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subscriptionid)
	{
		getMendixObject().setValue(context, MemberNames.SubscriptionID.toString(), subscriptionid);
	}

	/**
	 * @return value of MonitoredItemID
	 */
	public final java.lang.String getMonitoredItemID()
	{
		return getMonitoredItemID(getContext());
	}

	/**
	 * @param context
	 * @return value of MonitoredItemID
	 */
	public final java.lang.String getMonitoredItemID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MonitoredItemID.toString());
	}

	/**
	 * Set value of MonitoredItemID
	 * @param monitoreditemid
	 */
	public final void setMonitoredItemID(java.lang.String monitoreditemid)
	{
		setMonitoredItemID(getContext(), monitoreditemid);
	}

	/**
	 * Set value of MonitoredItemID
	 * @param context
	 * @param monitoreditemid
	 */
	public final void setMonitoredItemID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String monitoreditemid)
	{
		getMendixObject().setValue(context, MemberNames.MonitoredItemID.toString(), monitoreditemid);
	}

	/**
	 * @return value of Payload
	 */
	public final java.lang.String getPayload()
	{
		return getPayload(getContext());
	}

	/**
	 * @param context
	 * @return value of Payload
	 */
	public final java.lang.String getPayload(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Payload.toString());
	}

	/**
	 * Set value of Payload
	 * @param payload
	 */
	public final void setPayload(java.lang.String payload)
	{
		setPayload(getContext(), payload);
	}

	/**
	 * Set value of Payload
	 * @param context
	 * @param payload
	 */
	public final void setPayload(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String payload)
	{
		getMendixObject().setValue(context, MemberNames.Payload.toString(), payload);
	}

	/**
	 * @return value of StatusCodeName
	 */
	public final java.lang.String getStatusCodeName()
	{
		return getStatusCodeName(getContext());
	}

	/**
	 * @param context
	 * @return value of StatusCodeName
	 */
	public final java.lang.String getStatusCodeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StatusCodeName.toString());
	}

	/**
	 * Set value of StatusCodeName
	 * @param statuscodename
	 */
	public final void setStatusCodeName(java.lang.String statuscodename)
	{
		setStatusCodeName(getContext(), statuscodename);
	}

	/**
	 * Set value of StatusCodeName
	 * @param context
	 * @param statuscodename
	 */
	public final void setStatusCodeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String statuscodename)
	{
		getMendixObject().setValue(context, MemberNames.StatusCodeName.toString(), statuscodename);
	}

	/**
	 * @return value of SourceTime
	 */
	public final java.util.Date getSourceTime()
	{
		return getSourceTime(getContext());
	}

	/**
	 * @param context
	 * @return value of SourceTime
	 */
	public final java.util.Date getSourceTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.SourceTime.toString());
	}

	/**
	 * Set value of SourceTime
	 * @param sourcetime
	 */
	public final void setSourceTime(java.util.Date sourcetime)
	{
		setSourceTime(getContext(), sourcetime);
	}

	/**
	 * Set value of SourceTime
	 * @param context
	 * @param sourcetime
	 */
	public final void setSourceTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date sourcetime)
	{
		getMendixObject().setValue(context, MemberNames.SourceTime.toString(), sourcetime);
	}

	/**
	 * @return value of ServerTime
	 */
	public final java.util.Date getServerTime()
	{
		return getServerTime(getContext());
	}

	/**
	 * @param context
	 * @return value of ServerTime
	 */
	public final java.util.Date getServerTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ServerTime.toString());
	}

	/**
	 * Set value of ServerTime
	 * @param servertime
	 */
	public final void setServerTime(java.util.Date servertime)
	{
		setServerTime(getContext(), servertime);
	}

	/**
	 * Set value of ServerTime
	 * @param context
	 * @param servertime
	 */
	public final void setServerTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date servertime)
	{
		getMendixObject().setValue(context, MemberNames.ServerTime.toString(), servertime);
	}

	/**
	 * @return value of FullMessage
	 */
	public final java.lang.String getFullMessage()
	{
		return getFullMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of FullMessage
	 */
	public final java.lang.String getFullMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FullMessage.toString());
	}

	/**
	 * Set value of FullMessage
	 * @param fullmessage
	 */
	public final void setFullMessage(java.lang.String fullmessage)
	{
		setFullMessage(getContext(), fullmessage);
	}

	/**
	 * Set value of FullMessage
	 * @param context
	 * @param fullmessage
	 */
	public final void setFullMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fullmessage)
	{
		getMendixObject().setValue(context, MemberNames.FullMessage.toString(), fullmessage);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return messageMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final opcuaclientmx.proxies.Message that = (opcuaclientmx.proxies.Message) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "OpcUaClientMx.Message";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
