// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package opcuaclientmx.proxies;

public class MonitoredItem
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject monitoredItemMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OpcUaClientMx.MonitoredItem";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NodeId("NodeId"),
		SubscriptionID("SubscriptionID"),
		MonitoredItemID("MonitoredItemID"),
		OnMessageMicroflow("OnMessageMicroflow"),
		Status("Status"),
		LastSubscribedOn("LastSubscribedOn"),
		LastStateChange("LastStateChange"),
		LastMessage("LastMessage"),
		MonitoredItem_OpcUaServerCfg("OpcUaClientMx.MonitoredItem_OpcUaServerCfg"),
		MonitoredItem_Subscription("OpcUaClientMx.MonitoredItem_Subscription");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MonitoredItem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MonitoredItem(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject monitoredItemMendixObject)
	{
		if (monitoredItemMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, monitoredItemMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.monitoredItemMendixObject = monitoredItemMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MonitoredItem.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static opcuaclientmx.proxies.MonitoredItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return opcuaclientmx.proxies.MonitoredItem.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static opcuaclientmx.proxies.MonitoredItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new opcuaclientmx.proxies.MonitoredItem(context, mendixObject);
	}

	public static opcuaclientmx.proxies.MonitoredItem load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return opcuaclientmx.proxies.MonitoredItem.initialize(context, mendixObject);
	}

	public static java.util.List<opcuaclientmx.proxies.MonitoredItem> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> opcuaclientmx.proxies.MonitoredItem.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of NodeId
	 */
	public final java.lang.String getNodeId()
	{
		return getNodeId(getContext());
	}

	/**
	 * @param context
	 * @return value of NodeId
	 */
	public final java.lang.String getNodeId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NodeId.toString());
	}

	/**
	 * Set value of NodeId
	 * @param nodeid
	 */
	public final void setNodeId(java.lang.String nodeid)
	{
		setNodeId(getContext(), nodeid);
	}

	/**
	 * Set value of NodeId
	 * @param context
	 * @param nodeid
	 */
	public final void setNodeId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nodeid)
	{
		getMendixObject().setValue(context, MemberNames.NodeId.toString(), nodeid);
	}

	/**
	 * @return value of SubscriptionID
	 */
	public final java.lang.String getSubscriptionID()
	{
		return getSubscriptionID(getContext());
	}

	/**
	 * @param context
	 * @return value of SubscriptionID
	 */
	public final java.lang.String getSubscriptionID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SubscriptionID.toString());
	}

	/**
	 * Set value of SubscriptionID
	 * @param subscriptionid
	 */
	public final void setSubscriptionID(java.lang.String subscriptionid)
	{
		setSubscriptionID(getContext(), subscriptionid);
	}

	/**
	 * Set value of SubscriptionID
	 * @param context
	 * @param subscriptionid
	 */
	public final void setSubscriptionID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subscriptionid)
	{
		getMendixObject().setValue(context, MemberNames.SubscriptionID.toString(), subscriptionid);
	}

	/**
	 * @return value of MonitoredItemID
	 */
	public final java.lang.String getMonitoredItemID()
	{
		return getMonitoredItemID(getContext());
	}

	/**
	 * @param context
	 * @return value of MonitoredItemID
	 */
	public final java.lang.String getMonitoredItemID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MonitoredItemID.toString());
	}

	/**
	 * Set value of MonitoredItemID
	 * @param monitoreditemid
	 */
	public final void setMonitoredItemID(java.lang.String monitoreditemid)
	{
		setMonitoredItemID(getContext(), monitoreditemid);
	}

	/**
	 * Set value of MonitoredItemID
	 * @param context
	 * @param monitoreditemid
	 */
	public final void setMonitoredItemID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String monitoreditemid)
	{
		getMendixObject().setValue(context, MemberNames.MonitoredItemID.toString(), monitoreditemid);
	}

	/**
	 * @return value of OnMessageMicroflow
	 */
	public final java.lang.String getOnMessageMicroflow()
	{
		return getOnMessageMicroflow(getContext());
	}

	/**
	 * @param context
	 * @return value of OnMessageMicroflow
	 */
	public final java.lang.String getOnMessageMicroflow(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OnMessageMicroflow.toString());
	}

	/**
	 * Set value of OnMessageMicroflow
	 * @param onmessagemicroflow
	 */
	public final void setOnMessageMicroflow(java.lang.String onmessagemicroflow)
	{
		setOnMessageMicroflow(getContext(), onmessagemicroflow);
	}

	/**
	 * Set value of OnMessageMicroflow
	 * @param context
	 * @param onmessagemicroflow
	 */
	public final void setOnMessageMicroflow(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String onmessagemicroflow)
	{
		getMendixObject().setValue(context, MemberNames.OnMessageMicroflow.toString(), onmessagemicroflow);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final opcuaclientmx.proxies.SubscriptionStatus getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final opcuaclientmx.proxies.SubscriptionStatus getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null) {
			return null;
		}
		return opcuaclientmx.proxies.SubscriptionStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(opcuaclientmx.proxies.SubscriptionStatus status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, opcuaclientmx.proxies.SubscriptionStatus status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
		}
	}

	/**
	 * @return value of LastSubscribedOn
	 */
	public final java.util.Date getLastSubscribedOn()
	{
		return getLastSubscribedOn(getContext());
	}

	/**
	 * @param context
	 * @return value of LastSubscribedOn
	 */
	public final java.util.Date getLastSubscribedOn(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LastSubscribedOn.toString());
	}

	/**
	 * Set value of LastSubscribedOn
	 * @param lastsubscribedon
	 */
	public final void setLastSubscribedOn(java.util.Date lastsubscribedon)
	{
		setLastSubscribedOn(getContext(), lastsubscribedon);
	}

	/**
	 * Set value of LastSubscribedOn
	 * @param context
	 * @param lastsubscribedon
	 */
	public final void setLastSubscribedOn(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date lastsubscribedon)
	{
		getMendixObject().setValue(context, MemberNames.LastSubscribedOn.toString(), lastsubscribedon);
	}

	/**
	 * @return value of LastStateChange
	 */
	public final java.util.Date getLastStateChange()
	{
		return getLastStateChange(getContext());
	}

	/**
	 * @param context
	 * @return value of LastStateChange
	 */
	public final java.util.Date getLastStateChange(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LastStateChange.toString());
	}

	/**
	 * Set value of LastStateChange
	 * @param laststatechange
	 */
	public final void setLastStateChange(java.util.Date laststatechange)
	{
		setLastStateChange(getContext(), laststatechange);
	}

	/**
	 * Set value of LastStateChange
	 * @param context
	 * @param laststatechange
	 */
	public final void setLastStateChange(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date laststatechange)
	{
		getMendixObject().setValue(context, MemberNames.LastStateChange.toString(), laststatechange);
	}

	/**
	 * @return value of LastMessage
	 */
	public final java.util.Date getLastMessage()
	{
		return getLastMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of LastMessage
	 */
	public final java.util.Date getLastMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LastMessage.toString());
	}

	/**
	 * Set value of LastMessage
	 * @param lastmessage
	 */
	public final void setLastMessage(java.util.Date lastmessage)
	{
		setLastMessage(getContext(), lastmessage);
	}

	/**
	 * Set value of LastMessage
	 * @param context
	 * @param lastmessage
	 */
	public final void setLastMessage(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date lastmessage)
	{
		getMendixObject().setValue(context, MemberNames.LastMessage.toString(), lastmessage);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MonitoredItem_OpcUaServerCfg
	 */
	public final opcuaclientmx.proxies.OpcUaServerCfg getMonitoredItem_OpcUaServerCfg() throws com.mendix.core.CoreException
	{
		return getMonitoredItem_OpcUaServerCfg(getContext());
	}

	/**
	 * @param context
	 * @return value of MonitoredItem_OpcUaServerCfg
	 * @throws com.mendix.core.CoreException
	 */
	public final opcuaclientmx.proxies.OpcUaServerCfg getMonitoredItem_OpcUaServerCfg(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		opcuaclientmx.proxies.OpcUaServerCfg result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MonitoredItem_OpcUaServerCfg.toString());
		if (identifier != null) {
			result = opcuaclientmx.proxies.OpcUaServerCfg.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MonitoredItem_OpcUaServerCfg
	 * @param monitoreditem_opcuaservercfg
	 */
	public final void setMonitoredItem_OpcUaServerCfg(opcuaclientmx.proxies.OpcUaServerCfg monitoreditem_opcuaservercfg)
	{
		setMonitoredItem_OpcUaServerCfg(getContext(), monitoreditem_opcuaservercfg);
	}

	/**
	 * Set value of MonitoredItem_OpcUaServerCfg
	 * @param context
	 * @param monitoreditem_opcuaservercfg
	 */
	public final void setMonitoredItem_OpcUaServerCfg(com.mendix.systemwideinterfaces.core.IContext context, opcuaclientmx.proxies.OpcUaServerCfg monitoreditem_opcuaservercfg)
	{
		if (monitoreditem_opcuaservercfg == null) {
			getMendixObject().setValue(context, MemberNames.MonitoredItem_OpcUaServerCfg.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MonitoredItem_OpcUaServerCfg.toString(), monitoreditem_opcuaservercfg.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MonitoredItem_Subscription
	 */
	public final opcuaclientmx.proxies.Subscription getMonitoredItem_Subscription() throws com.mendix.core.CoreException
	{
		return getMonitoredItem_Subscription(getContext());
	}

	/**
	 * @param context
	 * @return value of MonitoredItem_Subscription
	 * @throws com.mendix.core.CoreException
	 */
	public final opcuaclientmx.proxies.Subscription getMonitoredItem_Subscription(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		opcuaclientmx.proxies.Subscription result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MonitoredItem_Subscription.toString());
		if (identifier != null) {
			result = opcuaclientmx.proxies.Subscription.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MonitoredItem_Subscription
	 * @param monitoreditem_subscription
	 */
	public final void setMonitoredItem_Subscription(opcuaclientmx.proxies.Subscription monitoreditem_subscription)
	{
		setMonitoredItem_Subscription(getContext(), monitoreditem_subscription);
	}

	/**
	 * Set value of MonitoredItem_Subscription
	 * @param context
	 * @param monitoreditem_subscription
	 */
	public final void setMonitoredItem_Subscription(com.mendix.systemwideinterfaces.core.IContext context, opcuaclientmx.proxies.Subscription monitoreditem_subscription)
	{
		if (monitoreditem_subscription == null) {
			getMendixObject().setValue(context, MemberNames.MonitoredItem_Subscription.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MonitoredItem_Subscription.toString(), monitoreditem_subscription.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return monitoredItemMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final opcuaclientmx.proxies.MonitoredItem that = (opcuaclientmx.proxies.MonitoredItem) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
