// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package opcuaclientmx.proxies;

public class Troubleshooting
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject troubleshootingMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OpcUaClientMx.Troubleshooting";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ValueToWrite("ValueToWrite"),
		NodeId("NodeId"),
		Result("Result"),
		Troubleshooting_OpcUaServerCfg("OpcUaClientMx.Troubleshooting_OpcUaServerCfg");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Troubleshooting(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Troubleshooting(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject troubleshootingMendixObject)
	{
		if (troubleshootingMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, troubleshootingMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.troubleshootingMendixObject = troubleshootingMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Troubleshooting.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static opcuaclientmx.proxies.Troubleshooting initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return opcuaclientmx.proxies.Troubleshooting.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static opcuaclientmx.proxies.Troubleshooting initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new opcuaclientmx.proxies.Troubleshooting(context, mendixObject);
	}

	public static opcuaclientmx.proxies.Troubleshooting load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return opcuaclientmx.proxies.Troubleshooting.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ValueToWrite
	 */
	public final java.lang.String getValueToWrite()
	{
		return getValueToWrite(getContext());
	}

	/**
	 * @param context
	 * @return value of ValueToWrite
	 */
	public final java.lang.String getValueToWrite(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ValueToWrite.toString());
	}

	/**
	 * Set value of ValueToWrite
	 * @param valuetowrite
	 */
	public final void setValueToWrite(java.lang.String valuetowrite)
	{
		setValueToWrite(getContext(), valuetowrite);
	}

	/**
	 * Set value of ValueToWrite
	 * @param context
	 * @param valuetowrite
	 */
	public final void setValueToWrite(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String valuetowrite)
	{
		getMendixObject().setValue(context, MemberNames.ValueToWrite.toString(), valuetowrite);
	}

	/**
	 * @return value of NodeId
	 */
	public final java.lang.String getNodeId()
	{
		return getNodeId(getContext());
	}

	/**
	 * @param context
	 * @return value of NodeId
	 */
	public final java.lang.String getNodeId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NodeId.toString());
	}

	/**
	 * Set value of NodeId
	 * @param nodeid
	 */
	public final void setNodeId(java.lang.String nodeid)
	{
		setNodeId(getContext(), nodeid);
	}

	/**
	 * Set value of NodeId
	 * @param context
	 * @param nodeid
	 */
	public final void setNodeId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nodeid)
	{
		getMendixObject().setValue(context, MemberNames.NodeId.toString(), nodeid);
	}

	/**
	 * @return value of Result
	 */
	public final java.lang.String getResult()
	{
		return getResult(getContext());
	}

	/**
	 * @param context
	 * @return value of Result
	 */
	public final java.lang.String getResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Result.toString());
	}

	/**
	 * Set value of Result
	 * @param result
	 */
	public final void setResult(java.lang.String result)
	{
		setResult(getContext(), result);
	}

	/**
	 * Set value of Result
	 * @param context
	 * @param result
	 */
	public final void setResult(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String result)
	{
		getMendixObject().setValue(context, MemberNames.Result.toString(), result);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Troubleshooting_OpcUaServerCfg
	 */
	public final opcuaclientmx.proxies.OpcUaServerCfg getTroubleshooting_OpcUaServerCfg() throws com.mendix.core.CoreException
	{
		return getTroubleshooting_OpcUaServerCfg(getContext());
	}

	/**
	 * @param context
	 * @return value of Troubleshooting_OpcUaServerCfg
	 * @throws com.mendix.core.CoreException
	 */
	public final opcuaclientmx.proxies.OpcUaServerCfg getTroubleshooting_OpcUaServerCfg(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		opcuaclientmx.proxies.OpcUaServerCfg result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Troubleshooting_OpcUaServerCfg.toString());
		if (identifier != null) {
			result = opcuaclientmx.proxies.OpcUaServerCfg.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Troubleshooting_OpcUaServerCfg
	 * @param troubleshooting_opcuaservercfg
	 */
	public final void setTroubleshooting_OpcUaServerCfg(opcuaclientmx.proxies.OpcUaServerCfg troubleshooting_opcuaservercfg)
	{
		setTroubleshooting_OpcUaServerCfg(getContext(), troubleshooting_opcuaservercfg);
	}

	/**
	 * Set value of Troubleshooting_OpcUaServerCfg
	 * @param context
	 * @param troubleshooting_opcuaservercfg
	 */
	public final void setTroubleshooting_OpcUaServerCfg(com.mendix.systemwideinterfaces.core.IContext context, opcuaclientmx.proxies.OpcUaServerCfg troubleshooting_opcuaservercfg)
	{
		if (troubleshooting_opcuaservercfg == null) {
			getMendixObject().setValue(context, MemberNames.Troubleshooting_OpcUaServerCfg.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Troubleshooting_OpcUaServerCfg.toString(), troubleshooting_opcuaservercfg.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return troubleshootingMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final opcuaclientmx.proxies.Troubleshooting that = (opcuaclientmx.proxies.Troubleshooting) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
