// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package opcuaclient_exampleimplementation.proxies;

public class DisplayName
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject displayNameMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OpcUaClient_ExampleImplementation.DisplayName";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Text("Text"),
		DisplayName_OpcUaNode("OpcUaClient_ExampleImplementation.DisplayName_OpcUaNode");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DisplayName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "OpcUaClient_ExampleImplementation.DisplayName"));
	}

	protected DisplayName(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject displayNameMendixObject)
	{
		if (displayNameMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("OpcUaClient_ExampleImplementation.DisplayName", displayNameMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a OpcUaClient_ExampleImplementation.DisplayName");

		this.displayNameMendixObject = displayNameMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DisplayName.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static opcuaclient_exampleimplementation.proxies.DisplayName initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return opcuaclient_exampleimplementation.proxies.DisplayName.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static opcuaclient_exampleimplementation.proxies.DisplayName initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new opcuaclient_exampleimplementation.proxies.DisplayName(context, mendixObject);
	}

	public static opcuaclient_exampleimplementation.proxies.DisplayName load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return opcuaclient_exampleimplementation.proxies.DisplayName.initialize(context, mendixObject);
	}

	public static java.util.List<opcuaclient_exampleimplementation.proxies.DisplayName> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<opcuaclient_exampleimplementation.proxies.DisplayName> result = new java.util.ArrayList<opcuaclient_exampleimplementation.proxies.DisplayName>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//OpcUaClient_ExampleImplementation.DisplayName" + xpathConstraint))
			result.add(opcuaclient_exampleimplementation.proxies.DisplayName.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Text
	 */
	public final java.lang.String getText()
	{
		return getText(getContext());
	}

	/**
	 * @param context
	 * @return value of Text
	 */
	public final java.lang.String getText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Text.toString());
	}

	/**
	 * Set value of Text
	 * @param text
	 */
	public final void setText(java.lang.String text)
	{
		setText(getContext(), text);
	}

	/**
	 * Set value of Text
	 * @param context
	 * @param text
	 */
	public final void setText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String text)
	{
		getMendixObject().setValue(context, MemberNames.Text.toString(), text);
	}

	/**
	 * @return value of DisplayName_OpcUaNode
	 */
	public final opcuaclient_exampleimplementation.proxies.OpcUaNode getDisplayName_OpcUaNode() throws com.mendix.core.CoreException
	{
		return getDisplayName_OpcUaNode(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayName_OpcUaNode
	 */
	public final opcuaclient_exampleimplementation.proxies.OpcUaNode getDisplayName_OpcUaNode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		opcuaclient_exampleimplementation.proxies.OpcUaNode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DisplayName_OpcUaNode.toString());
		if (identifier != null)
			result = opcuaclient_exampleimplementation.proxies.OpcUaNode.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DisplayName_OpcUaNode
	 * @param displayname_opcuanode
	 */
	public final void setDisplayName_OpcUaNode(opcuaclient_exampleimplementation.proxies.OpcUaNode displayname_opcuanode)
	{
		setDisplayName_OpcUaNode(getContext(), displayname_opcuanode);
	}

	/**
	 * Set value of DisplayName_OpcUaNode
	 * @param context
	 * @param displayname_opcuanode
	 */
	public final void setDisplayName_OpcUaNode(com.mendix.systemwideinterfaces.core.IContext context, opcuaclient_exampleimplementation.proxies.OpcUaNode displayname_opcuanode)
	{
		if (displayname_opcuanode == null)
			getMendixObject().setValue(context, MemberNames.DisplayName_OpcUaNode.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DisplayName_OpcUaNode.toString(), displayname_opcuanode.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return displayNameMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final opcuaclient_exampleimplementation.proxies.DisplayName that = (opcuaclient_exampleimplementation.proxies.DisplayName) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "OpcUaClient_ExampleImplementation.DisplayName";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
