// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package opcuaclient_exampleimplementation.proxies;

public class MonitoredItem
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject monitoredItemMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OpcUaClient_ExampleImplementation.MonitoredItem";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Payload("Payload"),
		SubscriptionID("SubscriptionID"),
		MonitoredItem_OpcUaNode("OpcUaClient_ExampleImplementation.MonitoredItem_OpcUaNode");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MonitoredItem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MonitoredItem(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject monitoredItemMendixObject)
	{
		if (monitoredItemMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, monitoredItemMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.monitoredItemMendixObject = monitoredItemMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MonitoredItem.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static opcuaclient_exampleimplementation.proxies.MonitoredItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return opcuaclient_exampleimplementation.proxies.MonitoredItem.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static opcuaclient_exampleimplementation.proxies.MonitoredItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new opcuaclient_exampleimplementation.proxies.MonitoredItem(context, mendixObject);
	}

	public static opcuaclient_exampleimplementation.proxies.MonitoredItem load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return opcuaclient_exampleimplementation.proxies.MonitoredItem.initialize(context, mendixObject);
	}

	public static java.util.List<opcuaclient_exampleimplementation.proxies.MonitoredItem> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> opcuaclient_exampleimplementation.proxies.MonitoredItem.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Payload
	 */
	public final java.lang.String getPayload()
	{
		return getPayload(getContext());
	}

	/**
	 * @param context
	 * @return value of Payload
	 */
	public final java.lang.String getPayload(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Payload.toString());
	}

	/**
	 * Set value of Payload
	 * @param payload
	 */
	public final void setPayload(java.lang.String payload)
	{
		setPayload(getContext(), payload);
	}

	/**
	 * Set value of Payload
	 * @param context
	 * @param payload
	 */
	public final void setPayload(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String payload)
	{
		getMendixObject().setValue(context, MemberNames.Payload.toString(), payload);
	}

	/**
	 * @return value of SubscriptionID
	 */
	public final java.lang.String getSubscriptionID()
	{
		return getSubscriptionID(getContext());
	}

	/**
	 * @param context
	 * @return value of SubscriptionID
	 */
	public final java.lang.String getSubscriptionID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SubscriptionID.toString());
	}

	/**
	 * Set value of SubscriptionID
	 * @param subscriptionid
	 */
	public final void setSubscriptionID(java.lang.String subscriptionid)
	{
		setSubscriptionID(getContext(), subscriptionid);
	}

	/**
	 * Set value of SubscriptionID
	 * @param context
	 * @param subscriptionid
	 */
	public final void setSubscriptionID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subscriptionid)
	{
		getMendixObject().setValue(context, MemberNames.SubscriptionID.toString(), subscriptionid);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MonitoredItem_OpcUaNode
	 */
	public final opcuaclient_exampleimplementation.proxies.OpcUaNode getMonitoredItem_OpcUaNode() throws com.mendix.core.CoreException
	{
		return getMonitoredItem_OpcUaNode(getContext());
	}

	/**
	 * @param context
	 * @return value of MonitoredItem_OpcUaNode
	 * @throws com.mendix.core.CoreException
	 */
	public final opcuaclient_exampleimplementation.proxies.OpcUaNode getMonitoredItem_OpcUaNode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		opcuaclient_exampleimplementation.proxies.OpcUaNode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MonitoredItem_OpcUaNode.toString());
		if (identifier != null) {
			result = opcuaclient_exampleimplementation.proxies.OpcUaNode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MonitoredItem_OpcUaNode
	 * @param monitoreditem_opcuanode
	 */
	public final void setMonitoredItem_OpcUaNode(opcuaclient_exampleimplementation.proxies.OpcUaNode monitoreditem_opcuanode)
	{
		setMonitoredItem_OpcUaNode(getContext(), monitoreditem_opcuanode);
	}

	/**
	 * Set value of MonitoredItem_OpcUaNode
	 * @param context
	 * @param monitoreditem_opcuanode
	 */
	public final void setMonitoredItem_OpcUaNode(com.mendix.systemwideinterfaces.core.IContext context, opcuaclient_exampleimplementation.proxies.OpcUaNode monitoreditem_opcuanode)
	{
		if (monitoreditem_opcuanode == null) {
			getMendixObject().setValue(context, MemberNames.MonitoredItem_OpcUaNode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MonitoredItem_OpcUaNode.toString(), monitoreditem_opcuanode.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return monitoredItemMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final opcuaclient_exampleimplementation.proxies.MonitoredItem that = (opcuaclient_exampleimplementation.proxies.MonitoredItem) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
