// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package opcuaclient_exampleimplementation.proxies;

public class OpcUaNode
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject opcUaNodeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OpcUaClient_ExampleImplementation.OpcUaNode";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NodeId("NodeId"),
		NodeClass("NodeClass"),
		DisplayName("DisplayName"),
		Description("Description"),
		Value("Value"),
		Historizing("Historizing"),
		Root("Root"),
		NamespaceIndex("NamespaceIndex"),
		Identifier("Identifier"),
		Result("Result"),
		BrowseName("BrowseName"),
		Name("Name"),
		ValueToWrite("ValueToWrite"),
		IsForward("IsForward"),
		HasChildren("HasChildren"),
		OpcUaServerCfgID("OpcUaServerCfgID"),
		OpcUaNode_Set("OpcUaClient_ExampleImplementation.OpcUaNode_Set"),
		Children("OpcUaClient_ExampleImplementation.Children"),
		Parent("OpcUaClient_ExampleImplementation.Parent"),
		ReferenceTypeId_OpcUaNode("OpcUaClient_ExampleImplementation.ReferenceTypeId_OpcUaNode"),
		NodeId_OpcUaNode("OpcUaClient_ExampleImplementation.NodeId_OpcUaNode"),
		BrowseName_OpcUaNode("OpcUaClient_ExampleImplementation.BrowseName_OpcUaNode"),
		DisplayName_OpcUaNode("OpcUaClient_ExampleImplementation.DisplayName_OpcUaNode"),
		TypeDefinition_OpcUaNode("OpcUaClient_ExampleImplementation.TypeDefinition_OpcUaNode"),
		XmlEncodingId_OpcUaNode("OpcUaClient_ExampleImplementation.XmlEncodingId_OpcUaNode"),
		BinaryEncodingId_OpcUaNode("OpcUaClient_ExampleImplementation.BinaryEncodingId_OpcUaNode"),
		TypeId_OpcUaNode("OpcUaClient_ExampleImplementation.TypeId_OpcUaNode");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OpcUaNode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "OpcUaClient_ExampleImplementation.OpcUaNode"));
	}

	protected OpcUaNode(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject opcUaNodeMendixObject)
	{
		if (opcUaNodeMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("OpcUaClient_ExampleImplementation.OpcUaNode", opcUaNodeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a OpcUaClient_ExampleImplementation.OpcUaNode");

		this.opcUaNodeMendixObject = opcUaNodeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'OpcUaNode.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static opcuaclient_exampleimplementation.proxies.OpcUaNode initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return opcuaclient_exampleimplementation.proxies.OpcUaNode.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static opcuaclient_exampleimplementation.proxies.OpcUaNode initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new opcuaclient_exampleimplementation.proxies.OpcUaNode(context, mendixObject);
	}

	public static opcuaclient_exampleimplementation.proxies.OpcUaNode load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return opcuaclient_exampleimplementation.proxies.OpcUaNode.initialize(context, mendixObject);
	}

	public static java.util.List<opcuaclient_exampleimplementation.proxies.OpcUaNode> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<opcuaclient_exampleimplementation.proxies.OpcUaNode> result = new java.util.ArrayList<opcuaclient_exampleimplementation.proxies.OpcUaNode>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//OpcUaClient_ExampleImplementation.OpcUaNode" + xpathConstraint))
			result.add(opcuaclient_exampleimplementation.proxies.OpcUaNode.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of NodeId
	 */
	public final java.lang.String getNodeId()
	{
		return getNodeId(getContext());
	}

	/**
	 * @param context
	 * @return value of NodeId
	 */
	public final java.lang.String getNodeId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NodeId.toString());
	}

	/**
	 * Set value of NodeId
	 * @param nodeid
	 */
	public final void setNodeId(java.lang.String nodeid)
	{
		setNodeId(getContext(), nodeid);
	}

	/**
	 * Set value of NodeId
	 * @param context
	 * @param nodeid
	 */
	public final void setNodeId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nodeid)
	{
		getMendixObject().setValue(context, MemberNames.NodeId.toString(), nodeid);
	}

	/**
	 * @return value of NodeClass
	 */
	public final java.lang.String getNodeClass()
	{
		return getNodeClass(getContext());
	}

	/**
	 * @param context
	 * @return value of NodeClass
	 */
	public final java.lang.String getNodeClass(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NodeClass.toString());
	}

	/**
	 * Set value of NodeClass
	 * @param nodeclass
	 */
	public final void setNodeClass(java.lang.String nodeclass)
	{
		setNodeClass(getContext(), nodeclass);
	}

	/**
	 * Set value of NodeClass
	 * @param context
	 * @param nodeclass
	 */
	public final void setNodeClass(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nodeclass)
	{
		getMendixObject().setValue(context, MemberNames.NodeClass.toString(), nodeclass);
	}

	/**
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName()
	{
		return getDisplayName(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayName
	 */
	public final java.lang.String getDisplayName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DisplayName.toString());
	}

	/**
	 * Set value of DisplayName
	 * @param displayname
	 */
	public final void setDisplayName(java.lang.String displayname)
	{
		setDisplayName(getContext(), displayname);
	}

	/**
	 * Set value of DisplayName
	 * @param context
	 * @param displayname
	 */
	public final void setDisplayName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String displayname)
	{
		getMendixObject().setValue(context, MemberNames.DisplayName.toString(), displayname);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of Value
	 */
	public final java.lang.String getValue()
	{
		return getValue(getContext());
	}

	/**
	 * @param context
	 * @return value of Value
	 */
	public final java.lang.String getValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Value.toString());
	}

	/**
	 * Set value of Value
	 * @param value
	 */
	public final void setValue(java.lang.String value)
	{
		setValue(getContext(), value);
	}

	/**
	 * Set value of Value
	 * @param context
	 * @param value
	 */
	public final void setValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String value)
	{
		getMendixObject().setValue(context, MemberNames.Value.toString(), value);
	}

	/**
	 * @return value of Historizing
	 */
	public final java.lang.Boolean getHistorizing()
	{
		return getHistorizing(getContext());
	}

	/**
	 * @param context
	 * @return value of Historizing
	 */
	public final java.lang.Boolean getHistorizing(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Historizing.toString());
	}

	/**
	 * Set value of Historizing
	 * @param historizing
	 */
	public final void setHistorizing(java.lang.Boolean historizing)
	{
		setHistorizing(getContext(), historizing);
	}

	/**
	 * Set value of Historizing
	 * @param context
	 * @param historizing
	 */
	public final void setHistorizing(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean historizing)
	{
		getMendixObject().setValue(context, MemberNames.Historizing.toString(), historizing);
	}

	/**
	 * @return value of Root
	 */
	public final java.lang.Boolean getRoot()
	{
		return getRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of Root
	 */
	public final java.lang.Boolean getRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Root.toString());
	}

	/**
	 * Set value of Root
	 * @param root
	 */
	public final void setRoot(java.lang.Boolean root)
	{
		setRoot(getContext(), root);
	}

	/**
	 * Set value of Root
	 * @param context
	 * @param root
	 */
	public final void setRoot(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean root)
	{
		getMendixObject().setValue(context, MemberNames.Root.toString(), root);
	}

	/**
	 * @return value of NamespaceIndex
	 */
	public final java.lang.String getNamespaceIndex()
	{
		return getNamespaceIndex(getContext());
	}

	/**
	 * @param context
	 * @return value of NamespaceIndex
	 */
	public final java.lang.String getNamespaceIndex(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NamespaceIndex.toString());
	}

	/**
	 * Set value of NamespaceIndex
	 * @param namespaceindex
	 */
	public final void setNamespaceIndex(java.lang.String namespaceindex)
	{
		setNamespaceIndex(getContext(), namespaceindex);
	}

	/**
	 * Set value of NamespaceIndex
	 * @param context
	 * @param namespaceindex
	 */
	public final void setNamespaceIndex(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String namespaceindex)
	{
		getMendixObject().setValue(context, MemberNames.NamespaceIndex.toString(), namespaceindex);
	}

	/**
	 * @return value of Identifier
	 */
	public final java.lang.String getIdentifier()
	{
		return getIdentifier(getContext());
	}

	/**
	 * @param context
	 * @return value of Identifier
	 */
	public final java.lang.String getIdentifier(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Identifier.toString());
	}

	/**
	 * Set value of Identifier
	 * @param identifier
	 */
	public final void setIdentifier(java.lang.String identifier)
	{
		setIdentifier(getContext(), identifier);
	}

	/**
	 * Set value of Identifier
	 * @param context
	 * @param identifier
	 */
	public final void setIdentifier(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String identifier)
	{
		getMendixObject().setValue(context, MemberNames.Identifier.toString(), identifier);
	}

	/**
	 * @return value of Result
	 */
	public final java.lang.String getResult()
	{
		return getResult(getContext());
	}

	/**
	 * @param context
	 * @return value of Result
	 */
	public final java.lang.String getResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Result.toString());
	}

	/**
	 * Set value of Result
	 * @param result
	 */
	public final void setResult(java.lang.String result)
	{
		setResult(getContext(), result);
	}

	/**
	 * Set value of Result
	 * @param context
	 * @param result
	 */
	public final void setResult(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String result)
	{
		getMendixObject().setValue(context, MemberNames.Result.toString(), result);
	}

	/**
	 * @return value of BrowseName
	 */
	public final java.lang.String getBrowseName()
	{
		return getBrowseName(getContext());
	}

	/**
	 * @param context
	 * @return value of BrowseName
	 */
	public final java.lang.String getBrowseName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BrowseName.toString());
	}

	/**
	 * Set value of BrowseName
	 * @param browsename
	 */
	public final void setBrowseName(java.lang.String browsename)
	{
		setBrowseName(getContext(), browsename);
	}

	/**
	 * Set value of BrowseName
	 * @param context
	 * @param browsename
	 */
	public final void setBrowseName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String browsename)
	{
		getMendixObject().setValue(context, MemberNames.BrowseName.toString(), browsename);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of ValueToWrite
	 */
	public final java.lang.String getValueToWrite()
	{
		return getValueToWrite(getContext());
	}

	/**
	 * @param context
	 * @return value of ValueToWrite
	 */
	public final java.lang.String getValueToWrite(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ValueToWrite.toString());
	}

	/**
	 * Set value of ValueToWrite
	 * @param valuetowrite
	 */
	public final void setValueToWrite(java.lang.String valuetowrite)
	{
		setValueToWrite(getContext(), valuetowrite);
	}

	/**
	 * Set value of ValueToWrite
	 * @param context
	 * @param valuetowrite
	 */
	public final void setValueToWrite(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String valuetowrite)
	{
		getMendixObject().setValue(context, MemberNames.ValueToWrite.toString(), valuetowrite);
	}

	/**
	 * @return value of IsForward
	 */
	public final java.lang.Boolean getIsForward()
	{
		return getIsForward(getContext());
	}

	/**
	 * @param context
	 * @return value of IsForward
	 */
	public final java.lang.Boolean getIsForward(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsForward.toString());
	}

	/**
	 * Set value of IsForward
	 * @param isforward
	 */
	public final void setIsForward(java.lang.Boolean isforward)
	{
		setIsForward(getContext(), isforward);
	}

	/**
	 * Set value of IsForward
	 * @param context
	 * @param isforward
	 */
	public final void setIsForward(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isforward)
	{
		getMendixObject().setValue(context, MemberNames.IsForward.toString(), isforward);
	}

	/**
	 * @return value of HasChildren
	 */
	public final java.lang.Boolean getHasChildren()
	{
		return getHasChildren(getContext());
	}

	/**
	 * @param context
	 * @return value of HasChildren
	 */
	public final java.lang.Boolean getHasChildren(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasChildren.toString());
	}

	/**
	 * Set value of HasChildren
	 * @param haschildren
	 */
	public final void setHasChildren(java.lang.Boolean haschildren)
	{
		setHasChildren(getContext(), haschildren);
	}

	/**
	 * Set value of HasChildren
	 * @param context
	 * @param haschildren
	 */
	public final void setHasChildren(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean haschildren)
	{
		getMendixObject().setValue(context, MemberNames.HasChildren.toString(), haschildren);
	}

	/**
	 * @return value of OpcUaServerCfgID
	 */
	public final java.lang.String getOpcUaServerCfgID()
	{
		return getOpcUaServerCfgID(getContext());
	}

	/**
	 * @param context
	 * @return value of OpcUaServerCfgID
	 */
	public final java.lang.String getOpcUaServerCfgID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OpcUaServerCfgID.toString());
	}

	/**
	 * Set value of OpcUaServerCfgID
	 * @param opcuaservercfgid
	 */
	public final void setOpcUaServerCfgID(java.lang.String opcuaservercfgid)
	{
		setOpcUaServerCfgID(getContext(), opcuaservercfgid);
	}

	/**
	 * Set value of OpcUaServerCfgID
	 * @param context
	 * @param opcuaservercfgid
	 */
	public final void setOpcUaServerCfgID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String opcuaservercfgid)
	{
		getMendixObject().setValue(context, MemberNames.OpcUaServerCfgID.toString(), opcuaservercfgid);
	}

	/**
	 * @return value of OpcUaNode_Set
	 */
	public final opcuaclient_exampleimplementation.proxies.Set getOpcUaNode_Set() throws com.mendix.core.CoreException
	{
		return getOpcUaNode_Set(getContext());
	}

	/**
	 * @param context
	 * @return value of OpcUaNode_Set
	 */
	public final opcuaclient_exampleimplementation.proxies.Set getOpcUaNode_Set(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		opcuaclient_exampleimplementation.proxies.Set result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OpcUaNode_Set.toString());
		if (identifier != null)
			result = opcuaclient_exampleimplementation.proxies.Set.load(context, identifier);
		return result;
	}

	/**
	 * Set value of OpcUaNode_Set
	 * @param opcuanode_set
	 */
	public final void setOpcUaNode_Set(opcuaclient_exampleimplementation.proxies.Set opcuanode_set)
	{
		setOpcUaNode_Set(getContext(), opcuanode_set);
	}

	/**
	 * Set value of OpcUaNode_Set
	 * @param context
	 * @param opcuanode_set
	 */
	public final void setOpcUaNode_Set(com.mendix.systemwideinterfaces.core.IContext context, opcuaclient_exampleimplementation.proxies.Set opcuanode_set)
	{
		if (opcuanode_set == null)
			getMendixObject().setValue(context, MemberNames.OpcUaNode_Set.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.OpcUaNode_Set.toString(), opcuanode_set.getMendixObject().getId());
	}

	/**
	 * @return value of Children
	 */
	public final java.util.List<opcuaclient_exampleimplementation.proxies.OpcUaNode> getChildren() throws com.mendix.core.CoreException
	{
		return getChildren(getContext());
	}

	/**
	 * @param context
	 * @return value of Children
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<opcuaclient_exampleimplementation.proxies.OpcUaNode> getChildren(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<opcuaclient_exampleimplementation.proxies.OpcUaNode> result = new java.util.ArrayList<opcuaclient_exampleimplementation.proxies.OpcUaNode>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Children.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(opcuaclient_exampleimplementation.proxies.OpcUaNode.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of Children
	 * @param children
	 */
	public final void setChildren(java.util.List<opcuaclient_exampleimplementation.proxies.OpcUaNode> children)
	{
		setChildren(getContext(), children);
	}

	/**
	 * Set value of Children
	 * @param context
	 * @param children
	 */
	public final void setChildren(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<opcuaclient_exampleimplementation.proxies.OpcUaNode> children)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (opcuaclient_exampleimplementation.proxies.OpcUaNode proxyObject : children)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.Children.toString(), identifiers);
	}

	/**
	 * @return value of Parent
	 */
	public final opcuaclient_exampleimplementation.proxies.OpcUaNode getParent() throws com.mendix.core.CoreException
	{
		return getParent(getContext());
	}

	/**
	 * @param context
	 * @return value of Parent
	 */
	public final opcuaclient_exampleimplementation.proxies.OpcUaNode getParent(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		opcuaclient_exampleimplementation.proxies.OpcUaNode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Parent.toString());
		if (identifier != null)
			result = opcuaclient_exampleimplementation.proxies.OpcUaNode.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Parent
	 * @param parent
	 */
	public final void setParent(opcuaclient_exampleimplementation.proxies.OpcUaNode parent)
	{
		setParent(getContext(), parent);
	}

	/**
	 * Set value of Parent
	 * @param context
	 * @param parent
	 */
	public final void setParent(com.mendix.systemwideinterfaces.core.IContext context, opcuaclient_exampleimplementation.proxies.OpcUaNode parent)
	{
		if (parent == null)
			getMendixObject().setValue(context, MemberNames.Parent.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Parent.toString(), parent.getMendixObject().getId());
	}

	/**
	 * @return value of ReferenceTypeId_OpcUaNode
	 */
	public final opcuaclient_exampleimplementation.proxies.ReferenceTypeId getReferenceTypeId_OpcUaNode() throws com.mendix.core.CoreException
	{
		return getReferenceTypeId_OpcUaNode(getContext());
	}

	/**
	 * @param context
	 * @return value of ReferenceTypeId_OpcUaNode
	 */
	public final opcuaclient_exampleimplementation.proxies.ReferenceTypeId getReferenceTypeId_OpcUaNode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		opcuaclient_exampleimplementation.proxies.ReferenceTypeId result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ReferenceTypeId_OpcUaNode.toString());
		if (identifier != null)
			result = opcuaclient_exampleimplementation.proxies.ReferenceTypeId.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ReferenceTypeId_OpcUaNode
	 * @param referencetypeid_opcuanode
	 */
	public final void setReferenceTypeId_OpcUaNode(opcuaclient_exampleimplementation.proxies.ReferenceTypeId referencetypeid_opcuanode)
	{
		setReferenceTypeId_OpcUaNode(getContext(), referencetypeid_opcuanode);
	}

	/**
	 * Set value of ReferenceTypeId_OpcUaNode
	 * @param context
	 * @param referencetypeid_opcuanode
	 */
	public final void setReferenceTypeId_OpcUaNode(com.mendix.systemwideinterfaces.core.IContext context, opcuaclient_exampleimplementation.proxies.ReferenceTypeId referencetypeid_opcuanode)
	{
		if (referencetypeid_opcuanode == null)
			getMendixObject().setValue(context, MemberNames.ReferenceTypeId_OpcUaNode.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ReferenceTypeId_OpcUaNode.toString(), referencetypeid_opcuanode.getMendixObject().getId());
	}

	/**
	 * @return value of NodeId_OpcUaNode
	 */
	public final opcuaclient_exampleimplementation.proxies.NodeId getNodeId_OpcUaNode() throws com.mendix.core.CoreException
	{
		return getNodeId_OpcUaNode(getContext());
	}

	/**
	 * @param context
	 * @return value of NodeId_OpcUaNode
	 */
	public final opcuaclient_exampleimplementation.proxies.NodeId getNodeId_OpcUaNode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		opcuaclient_exampleimplementation.proxies.NodeId result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.NodeId_OpcUaNode.toString());
		if (identifier != null)
			result = opcuaclient_exampleimplementation.proxies.NodeId.load(context, identifier);
		return result;
	}

	/**
	 * Set value of NodeId_OpcUaNode
	 * @param nodeid_opcuanode
	 */
	public final void setNodeId_OpcUaNode(opcuaclient_exampleimplementation.proxies.NodeId nodeid_opcuanode)
	{
		setNodeId_OpcUaNode(getContext(), nodeid_opcuanode);
	}

	/**
	 * Set value of NodeId_OpcUaNode
	 * @param context
	 * @param nodeid_opcuanode
	 */
	public final void setNodeId_OpcUaNode(com.mendix.systemwideinterfaces.core.IContext context, opcuaclient_exampleimplementation.proxies.NodeId nodeid_opcuanode)
	{
		if (nodeid_opcuanode == null)
			getMendixObject().setValue(context, MemberNames.NodeId_OpcUaNode.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.NodeId_OpcUaNode.toString(), nodeid_opcuanode.getMendixObject().getId());
	}

	/**
	 * @return value of BrowseName_OpcUaNode
	 */
	public final opcuaclient_exampleimplementation.proxies.BrowseName getBrowseName_OpcUaNode() throws com.mendix.core.CoreException
	{
		return getBrowseName_OpcUaNode(getContext());
	}

	/**
	 * @param context
	 * @return value of BrowseName_OpcUaNode
	 */
	public final opcuaclient_exampleimplementation.proxies.BrowseName getBrowseName_OpcUaNode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		opcuaclient_exampleimplementation.proxies.BrowseName result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BrowseName_OpcUaNode.toString());
		if (identifier != null)
			result = opcuaclient_exampleimplementation.proxies.BrowseName.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BrowseName_OpcUaNode
	 * @param browsename_opcuanode
	 */
	public final void setBrowseName_OpcUaNode(opcuaclient_exampleimplementation.proxies.BrowseName browsename_opcuanode)
	{
		setBrowseName_OpcUaNode(getContext(), browsename_opcuanode);
	}

	/**
	 * Set value of BrowseName_OpcUaNode
	 * @param context
	 * @param browsename_opcuanode
	 */
	public final void setBrowseName_OpcUaNode(com.mendix.systemwideinterfaces.core.IContext context, opcuaclient_exampleimplementation.proxies.BrowseName browsename_opcuanode)
	{
		if (browsename_opcuanode == null)
			getMendixObject().setValue(context, MemberNames.BrowseName_OpcUaNode.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BrowseName_OpcUaNode.toString(), browsename_opcuanode.getMendixObject().getId());
	}

	/**
	 * @return value of DisplayName_OpcUaNode
	 */
	public final opcuaclient_exampleimplementation.proxies.DisplayName getDisplayName_OpcUaNode() throws com.mendix.core.CoreException
	{
		return getDisplayName_OpcUaNode(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayName_OpcUaNode
	 */
	public final opcuaclient_exampleimplementation.proxies.DisplayName getDisplayName_OpcUaNode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		opcuaclient_exampleimplementation.proxies.DisplayName result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DisplayName_OpcUaNode.toString());
		if (identifier != null)
			result = opcuaclient_exampleimplementation.proxies.DisplayName.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DisplayName_OpcUaNode
	 * @param displayname_opcuanode
	 */
	public final void setDisplayName_OpcUaNode(opcuaclient_exampleimplementation.proxies.DisplayName displayname_opcuanode)
	{
		setDisplayName_OpcUaNode(getContext(), displayname_opcuanode);
	}

	/**
	 * Set value of DisplayName_OpcUaNode
	 * @param context
	 * @param displayname_opcuanode
	 */
	public final void setDisplayName_OpcUaNode(com.mendix.systemwideinterfaces.core.IContext context, opcuaclient_exampleimplementation.proxies.DisplayName displayname_opcuanode)
	{
		if (displayname_opcuanode == null)
			getMendixObject().setValue(context, MemberNames.DisplayName_OpcUaNode.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DisplayName_OpcUaNode.toString(), displayname_opcuanode.getMendixObject().getId());
	}

	/**
	 * @return value of TypeDefinition_OpcUaNode
	 */
	public final opcuaclient_exampleimplementation.proxies.TypeDefinition getTypeDefinition_OpcUaNode() throws com.mendix.core.CoreException
	{
		return getTypeDefinition_OpcUaNode(getContext());
	}

	/**
	 * @param context
	 * @return value of TypeDefinition_OpcUaNode
	 */
	public final opcuaclient_exampleimplementation.proxies.TypeDefinition getTypeDefinition_OpcUaNode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		opcuaclient_exampleimplementation.proxies.TypeDefinition result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TypeDefinition_OpcUaNode.toString());
		if (identifier != null)
			result = opcuaclient_exampleimplementation.proxies.TypeDefinition.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TypeDefinition_OpcUaNode
	 * @param typedefinition_opcuanode
	 */
	public final void setTypeDefinition_OpcUaNode(opcuaclient_exampleimplementation.proxies.TypeDefinition typedefinition_opcuanode)
	{
		setTypeDefinition_OpcUaNode(getContext(), typedefinition_opcuanode);
	}

	/**
	 * Set value of TypeDefinition_OpcUaNode
	 * @param context
	 * @param typedefinition_opcuanode
	 */
	public final void setTypeDefinition_OpcUaNode(com.mendix.systemwideinterfaces.core.IContext context, opcuaclient_exampleimplementation.proxies.TypeDefinition typedefinition_opcuanode)
	{
		if (typedefinition_opcuanode == null)
			getMendixObject().setValue(context, MemberNames.TypeDefinition_OpcUaNode.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TypeDefinition_OpcUaNode.toString(), typedefinition_opcuanode.getMendixObject().getId());
	}

	/**
	 * @return value of XmlEncodingId_OpcUaNode
	 */
	public final opcuaclient_exampleimplementation.proxies.XmlEncodingId getXmlEncodingId_OpcUaNode() throws com.mendix.core.CoreException
	{
		return getXmlEncodingId_OpcUaNode(getContext());
	}

	/**
	 * @param context
	 * @return value of XmlEncodingId_OpcUaNode
	 */
	public final opcuaclient_exampleimplementation.proxies.XmlEncodingId getXmlEncodingId_OpcUaNode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		opcuaclient_exampleimplementation.proxies.XmlEncodingId result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.XmlEncodingId_OpcUaNode.toString());
		if (identifier != null)
			result = opcuaclient_exampleimplementation.proxies.XmlEncodingId.load(context, identifier);
		return result;
	}

	/**
	 * Set value of XmlEncodingId_OpcUaNode
	 * @param xmlencodingid_opcuanode
	 */
	public final void setXmlEncodingId_OpcUaNode(opcuaclient_exampleimplementation.proxies.XmlEncodingId xmlencodingid_opcuanode)
	{
		setXmlEncodingId_OpcUaNode(getContext(), xmlencodingid_opcuanode);
	}

	/**
	 * Set value of XmlEncodingId_OpcUaNode
	 * @param context
	 * @param xmlencodingid_opcuanode
	 */
	public final void setXmlEncodingId_OpcUaNode(com.mendix.systemwideinterfaces.core.IContext context, opcuaclient_exampleimplementation.proxies.XmlEncodingId xmlencodingid_opcuanode)
	{
		if (xmlencodingid_opcuanode == null)
			getMendixObject().setValue(context, MemberNames.XmlEncodingId_OpcUaNode.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.XmlEncodingId_OpcUaNode.toString(), xmlencodingid_opcuanode.getMendixObject().getId());
	}

	/**
	 * @return value of BinaryEncodingId_OpcUaNode
	 */
	public final opcuaclient_exampleimplementation.proxies.BinaryEncodingId getBinaryEncodingId_OpcUaNode() throws com.mendix.core.CoreException
	{
		return getBinaryEncodingId_OpcUaNode(getContext());
	}

	/**
	 * @param context
	 * @return value of BinaryEncodingId_OpcUaNode
	 */
	public final opcuaclient_exampleimplementation.proxies.BinaryEncodingId getBinaryEncodingId_OpcUaNode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		opcuaclient_exampleimplementation.proxies.BinaryEncodingId result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BinaryEncodingId_OpcUaNode.toString());
		if (identifier != null)
			result = opcuaclient_exampleimplementation.proxies.BinaryEncodingId.load(context, identifier);
		return result;
	}

	/**
	 * Set value of BinaryEncodingId_OpcUaNode
	 * @param binaryencodingid_opcuanode
	 */
	public final void setBinaryEncodingId_OpcUaNode(opcuaclient_exampleimplementation.proxies.BinaryEncodingId binaryencodingid_opcuanode)
	{
		setBinaryEncodingId_OpcUaNode(getContext(), binaryencodingid_opcuanode);
	}

	/**
	 * Set value of BinaryEncodingId_OpcUaNode
	 * @param context
	 * @param binaryencodingid_opcuanode
	 */
	public final void setBinaryEncodingId_OpcUaNode(com.mendix.systemwideinterfaces.core.IContext context, opcuaclient_exampleimplementation.proxies.BinaryEncodingId binaryencodingid_opcuanode)
	{
		if (binaryencodingid_opcuanode == null)
			getMendixObject().setValue(context, MemberNames.BinaryEncodingId_OpcUaNode.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.BinaryEncodingId_OpcUaNode.toString(), binaryencodingid_opcuanode.getMendixObject().getId());
	}

	/**
	 * @return value of TypeId_OpcUaNode
	 */
	public final opcuaclient_exampleimplementation.proxies.TypeId getTypeId_OpcUaNode() throws com.mendix.core.CoreException
	{
		return getTypeId_OpcUaNode(getContext());
	}

	/**
	 * @param context
	 * @return value of TypeId_OpcUaNode
	 */
	public final opcuaclient_exampleimplementation.proxies.TypeId getTypeId_OpcUaNode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		opcuaclient_exampleimplementation.proxies.TypeId result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TypeId_OpcUaNode.toString());
		if (identifier != null)
			result = opcuaclient_exampleimplementation.proxies.TypeId.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TypeId_OpcUaNode
	 * @param typeid_opcuanode
	 */
	public final void setTypeId_OpcUaNode(opcuaclient_exampleimplementation.proxies.TypeId typeid_opcuanode)
	{
		setTypeId_OpcUaNode(getContext(), typeid_opcuanode);
	}

	/**
	 * Set value of TypeId_OpcUaNode
	 * @param context
	 * @param typeid_opcuanode
	 */
	public final void setTypeId_OpcUaNode(com.mendix.systemwideinterfaces.core.IContext context, opcuaclient_exampleimplementation.proxies.TypeId typeid_opcuanode)
	{
		if (typeid_opcuanode == null)
			getMendixObject().setValue(context, MemberNames.TypeId_OpcUaNode.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TypeId_OpcUaNode.toString(), typeid_opcuanode.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return opcUaNodeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final opcuaclient_exampleimplementation.proxies.OpcUaNode that = (opcuaclient_exampleimplementation.proxies.OpcUaNode) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "OpcUaClient_ExampleImplementation.OpcUaNode";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
