// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package opcuaclient_exampleimplementation.proxies;

public class TypeDefinition
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject typeDefinitionMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "OpcUaClient_ExampleImplementation.TypeDefinition";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NamespaceIndex("NamespaceIndex"),
		Identifier("Identifier"),
		ServerIndex("ServerIndex"),
		Absolute("Absolute"),
		_type("_type"),
		Relative("Relative"),
		_null("_null"),
		NotNull("NotNull"),
		Local("Local"),
		TypeDefinition_OpcUaNode("OpcUaClient_ExampleImplementation.TypeDefinition_OpcUaNode");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TypeDefinition(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TypeDefinition(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject typeDefinitionMendixObject)
	{
		if (typeDefinitionMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, typeDefinitionMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.typeDefinitionMendixObject = typeDefinitionMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TypeDefinition.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static opcuaclient_exampleimplementation.proxies.TypeDefinition initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return opcuaclient_exampleimplementation.proxies.TypeDefinition.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static opcuaclient_exampleimplementation.proxies.TypeDefinition initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new opcuaclient_exampleimplementation.proxies.TypeDefinition(context, mendixObject);
	}

	public static opcuaclient_exampleimplementation.proxies.TypeDefinition load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return opcuaclient_exampleimplementation.proxies.TypeDefinition.initialize(context, mendixObject);
	}

	public static java.util.List<opcuaclient_exampleimplementation.proxies.TypeDefinition> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> opcuaclient_exampleimplementation.proxies.TypeDefinition.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of NamespaceIndex
	 */
	public final java.lang.Integer getNamespaceIndex()
	{
		return getNamespaceIndex(getContext());
	}

	/**
	 * @param context
	 * @return value of NamespaceIndex
	 */
	public final java.lang.Integer getNamespaceIndex(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NamespaceIndex.toString());
	}

	/**
	 * Set value of NamespaceIndex
	 * @param namespaceindex
	 */
	public final void setNamespaceIndex(java.lang.Integer namespaceindex)
	{
		setNamespaceIndex(getContext(), namespaceindex);
	}

	/**
	 * Set value of NamespaceIndex
	 * @param context
	 * @param namespaceindex
	 */
	public final void setNamespaceIndex(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer namespaceindex)
	{
		getMendixObject().setValue(context, MemberNames.NamespaceIndex.toString(), namespaceindex);
	}

	/**
	 * @return value of Identifier
	 */
	public final java.lang.String getIdentifier()
	{
		return getIdentifier(getContext());
	}

	/**
	 * @param context
	 * @return value of Identifier
	 */
	public final java.lang.String getIdentifier(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Identifier.toString());
	}

	/**
	 * Set value of Identifier
	 * @param identifier
	 */
	public final void setIdentifier(java.lang.String identifier)
	{
		setIdentifier(getContext(), identifier);
	}

	/**
	 * Set value of Identifier
	 * @param context
	 * @param identifier
	 */
	public final void setIdentifier(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String identifier)
	{
		getMendixObject().setValue(context, MemberNames.Identifier.toString(), identifier);
	}

	/**
	 * @return value of ServerIndex
	 */
	public final java.lang.Integer getServerIndex()
	{
		return getServerIndex(getContext());
	}

	/**
	 * @param context
	 * @return value of ServerIndex
	 */
	public final java.lang.Integer getServerIndex(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ServerIndex.toString());
	}

	/**
	 * Set value of ServerIndex
	 * @param serverindex
	 */
	public final void setServerIndex(java.lang.Integer serverindex)
	{
		setServerIndex(getContext(), serverindex);
	}

	/**
	 * Set value of ServerIndex
	 * @param context
	 * @param serverindex
	 */
	public final void setServerIndex(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer serverindex)
	{
		getMendixObject().setValue(context, MemberNames.ServerIndex.toString(), serverindex);
	}

	/**
	 * @return value of Absolute
	 */
	public final java.lang.Boolean getAbsolute()
	{
		return getAbsolute(getContext());
	}

	/**
	 * @param context
	 * @return value of Absolute
	 */
	public final java.lang.Boolean getAbsolute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Absolute.toString());
	}

	/**
	 * Set value of Absolute
	 * @param absolute
	 */
	public final void setAbsolute(java.lang.Boolean absolute)
	{
		setAbsolute(getContext(), absolute);
	}

	/**
	 * Set value of Absolute
	 * @param context
	 * @param absolute
	 */
	public final void setAbsolute(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean absolute)
	{
		getMendixObject().setValue(context, MemberNames.Absolute.toString(), absolute);
	}

	/**
	 * @return value of _type
	 */
	public final java.lang.String get_type()
	{
		return get_type(getContext());
	}

	/**
	 * @param context
	 * @return value of _type
	 */
	public final java.lang.String get_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._type.toString());
	}

	/**
	 * Set value of _type
	 * @param _type
	 */
	public final void set_type(java.lang.String _type)
	{
		set_type(getContext(), _type);
	}

	/**
	 * Set value of _type
	 * @param context
	 * @param _type
	 */
	public final void set_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _type)
	{
		getMendixObject().setValue(context, MemberNames._type.toString(), _type);
	}

	/**
	 * @return value of Relative
	 */
	public final java.lang.Boolean getRelative()
	{
		return getRelative(getContext());
	}

	/**
	 * @param context
	 * @return value of Relative
	 */
	public final java.lang.Boolean getRelative(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Relative.toString());
	}

	/**
	 * Set value of Relative
	 * @param relative
	 */
	public final void setRelative(java.lang.Boolean relative)
	{
		setRelative(getContext(), relative);
	}

	/**
	 * Set value of Relative
	 * @param context
	 * @param relative
	 */
	public final void setRelative(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean relative)
	{
		getMendixObject().setValue(context, MemberNames.Relative.toString(), relative);
	}

	/**
	 * @return value of _null
	 */
	public final java.lang.Boolean get_null()
	{
		return get_null(getContext());
	}

	/**
	 * @param context
	 * @return value of _null
	 */
	public final java.lang.Boolean get_null(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames._null.toString());
	}

	/**
	 * Set value of _null
	 * @param _null
	 */
	public final void set_null(java.lang.Boolean _null)
	{
		set_null(getContext(), _null);
	}

	/**
	 * Set value of _null
	 * @param context
	 * @param _null
	 */
	public final void set_null(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean _null)
	{
		getMendixObject().setValue(context, MemberNames._null.toString(), _null);
	}

	/**
	 * @return value of NotNull
	 */
	public final java.lang.Boolean getNotNull()
	{
		return getNotNull(getContext());
	}

	/**
	 * @param context
	 * @return value of NotNull
	 */
	public final java.lang.Boolean getNotNull(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.NotNull.toString());
	}

	/**
	 * Set value of NotNull
	 * @param notnull
	 */
	public final void setNotNull(java.lang.Boolean notnull)
	{
		setNotNull(getContext(), notnull);
	}

	/**
	 * Set value of NotNull
	 * @param context
	 * @param notnull
	 */
	public final void setNotNull(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean notnull)
	{
		getMendixObject().setValue(context, MemberNames.NotNull.toString(), notnull);
	}

	/**
	 * @return value of Local
	 */
	public final java.lang.Boolean getLocal()
	{
		return getLocal(getContext());
	}

	/**
	 * @param context
	 * @return value of Local
	 */
	public final java.lang.Boolean getLocal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Local.toString());
	}

	/**
	 * Set value of Local
	 * @param local
	 */
	public final void setLocal(java.lang.Boolean local)
	{
		setLocal(getContext(), local);
	}

	/**
	 * Set value of Local
	 * @param context
	 * @param local
	 */
	public final void setLocal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean local)
	{
		getMendixObject().setValue(context, MemberNames.Local.toString(), local);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TypeDefinition_OpcUaNode
	 */
	public final opcuaclient_exampleimplementation.proxies.OpcUaNode getTypeDefinition_OpcUaNode() throws com.mendix.core.CoreException
	{
		return getTypeDefinition_OpcUaNode(getContext());
	}

	/**
	 * @param context
	 * @return value of TypeDefinition_OpcUaNode
	 * @throws com.mendix.core.CoreException
	 */
	public final opcuaclient_exampleimplementation.proxies.OpcUaNode getTypeDefinition_OpcUaNode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		opcuaclient_exampleimplementation.proxies.OpcUaNode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TypeDefinition_OpcUaNode.toString());
		if (identifier != null) {
			result = opcuaclient_exampleimplementation.proxies.OpcUaNode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TypeDefinition_OpcUaNode
	 * @param typedefinition_opcuanode
	 */
	public final void setTypeDefinition_OpcUaNode(opcuaclient_exampleimplementation.proxies.OpcUaNode typedefinition_opcuanode)
	{
		setTypeDefinition_OpcUaNode(getContext(), typedefinition_opcuanode);
	}

	/**
	 * Set value of TypeDefinition_OpcUaNode
	 * @param context
	 * @param typedefinition_opcuanode
	 */
	public final void setTypeDefinition_OpcUaNode(com.mendix.systemwideinterfaces.core.IContext context, opcuaclient_exampleimplementation.proxies.OpcUaNode typedefinition_opcuanode)
	{
		if (typedefinition_opcuanode == null) {
			getMendixObject().setValue(context, MemberNames.TypeDefinition_OpcUaNode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TypeDefinition_OpcUaNode.toString(), typedefinition_opcuanode.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return typeDefinitionMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final opcuaclient_exampleimplementation.proxies.TypeDefinition that = (opcuaclient_exampleimplementation.proxies.TypeDefinition) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
