// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package implementation_2_onegenericevent.proxies;

public class GatePLC
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject gatePLCMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Implementation_2_OneGenericEvent.GatePLC";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		State("State"),
		Node_Cmd_Up("Node_Cmd_Up"),
		Node_Cmd_Down("Node_Cmd_Down"),
		Node_IsDown("Node_IsDown"),
		Node_IsUp("Node_IsUp"),
		Node_IsMoving("Node_IsMoving"),
		Configured("Configured"),
		GatePLC_MonitoredItem("Implementation_2_OneGenericEvent.GatePLC_MonitoredItem"),
		GatePLC_OpcUaServerCfg("Implementation_2_OneGenericEvent.GatePLC_OpcUaServerCfg");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GatePLC(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Implementation_2_OneGenericEvent.GatePLC"));
	}

	protected GatePLC(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject gatePLCMendixObject)
	{
		if (gatePLCMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Implementation_2_OneGenericEvent.GatePLC", gatePLCMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Implementation_2_OneGenericEvent.GatePLC");

		this.gatePLCMendixObject = gatePLCMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'GatePLC.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static implementation_2_onegenericevent.proxies.GatePLC initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return implementation_2_onegenericevent.proxies.GatePLC.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static implementation_2_onegenericevent.proxies.GatePLC initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new implementation_2_onegenericevent.proxies.GatePLC(context, mendixObject);
	}

	public static implementation_2_onegenericevent.proxies.GatePLC load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return implementation_2_onegenericevent.proxies.GatePLC.initialize(context, mendixObject);
	}

	public static java.util.List<implementation_2_onegenericevent.proxies.GatePLC> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<implementation_2_onegenericevent.proxies.GatePLC> result = new java.util.ArrayList<implementation_2_onegenericevent.proxies.GatePLC>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Implementation_2_OneGenericEvent.GatePLC" + xpathConstraint))
			result.add(implementation_2_onegenericevent.proxies.GatePLC.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of State
	 * @param state
	 */
	public final implementation_2_onegenericevent.proxies.GateState getState()
	{
		return getState(getContext());
	}

	/**
	 * @param context
	 * @return value of State
	 */
	public final implementation_2_onegenericevent.proxies.GateState getState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.State.toString());
		if (obj == null)
			return null;

		return implementation_2_onegenericevent.proxies.GateState.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final void setState(implementation_2_onegenericevent.proxies.GateState state)
	{
		setState(getContext(), state);
	}

	/**
	 * Set value of State
	 * @param context
	 * @param state
	 */
	public final void setState(com.mendix.systemwideinterfaces.core.IContext context, implementation_2_onegenericevent.proxies.GateState state)
	{
		if (state != null)
			getMendixObject().setValue(context, MemberNames.State.toString(), state.toString());
		else
			getMendixObject().setValue(context, MemberNames.State.toString(), null);
	}

	/**
	 * @return value of Node_Cmd_Up
	 */
	public final java.lang.String getNode_Cmd_Up()
	{
		return getNode_Cmd_Up(getContext());
	}

	/**
	 * @param context
	 * @return value of Node_Cmd_Up
	 */
	public final java.lang.String getNode_Cmd_Up(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Node_Cmd_Up.toString());
	}

	/**
	 * Set value of Node_Cmd_Up
	 * @param node_cmd_up
	 */
	public final void setNode_Cmd_Up(java.lang.String node_cmd_up)
	{
		setNode_Cmd_Up(getContext(), node_cmd_up);
	}

	/**
	 * Set value of Node_Cmd_Up
	 * @param context
	 * @param node_cmd_up
	 */
	public final void setNode_Cmd_Up(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String node_cmd_up)
	{
		getMendixObject().setValue(context, MemberNames.Node_Cmd_Up.toString(), node_cmd_up);
	}

	/**
	 * @return value of Node_Cmd_Down
	 */
	public final java.lang.String getNode_Cmd_Down()
	{
		return getNode_Cmd_Down(getContext());
	}

	/**
	 * @param context
	 * @return value of Node_Cmd_Down
	 */
	public final java.lang.String getNode_Cmd_Down(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Node_Cmd_Down.toString());
	}

	/**
	 * Set value of Node_Cmd_Down
	 * @param node_cmd_down
	 */
	public final void setNode_Cmd_Down(java.lang.String node_cmd_down)
	{
		setNode_Cmd_Down(getContext(), node_cmd_down);
	}

	/**
	 * Set value of Node_Cmd_Down
	 * @param context
	 * @param node_cmd_down
	 */
	public final void setNode_Cmd_Down(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String node_cmd_down)
	{
		getMendixObject().setValue(context, MemberNames.Node_Cmd_Down.toString(), node_cmd_down);
	}

	/**
	 * @return value of Node_IsDown
	 */
	public final java.lang.String getNode_IsDown()
	{
		return getNode_IsDown(getContext());
	}

	/**
	 * @param context
	 * @return value of Node_IsDown
	 */
	public final java.lang.String getNode_IsDown(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Node_IsDown.toString());
	}

	/**
	 * Set value of Node_IsDown
	 * @param node_isdown
	 */
	public final void setNode_IsDown(java.lang.String node_isdown)
	{
		setNode_IsDown(getContext(), node_isdown);
	}

	/**
	 * Set value of Node_IsDown
	 * @param context
	 * @param node_isdown
	 */
	public final void setNode_IsDown(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String node_isdown)
	{
		getMendixObject().setValue(context, MemberNames.Node_IsDown.toString(), node_isdown);
	}

	/**
	 * @return value of Node_IsUp
	 */
	public final java.lang.String getNode_IsUp()
	{
		return getNode_IsUp(getContext());
	}

	/**
	 * @param context
	 * @return value of Node_IsUp
	 */
	public final java.lang.String getNode_IsUp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Node_IsUp.toString());
	}

	/**
	 * Set value of Node_IsUp
	 * @param node_isup
	 */
	public final void setNode_IsUp(java.lang.String node_isup)
	{
		setNode_IsUp(getContext(), node_isup);
	}

	/**
	 * Set value of Node_IsUp
	 * @param context
	 * @param node_isup
	 */
	public final void setNode_IsUp(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String node_isup)
	{
		getMendixObject().setValue(context, MemberNames.Node_IsUp.toString(), node_isup);
	}

	/**
	 * @return value of Node_IsMoving
	 */
	public final java.lang.String getNode_IsMoving()
	{
		return getNode_IsMoving(getContext());
	}

	/**
	 * @param context
	 * @return value of Node_IsMoving
	 */
	public final java.lang.String getNode_IsMoving(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Node_IsMoving.toString());
	}

	/**
	 * Set value of Node_IsMoving
	 * @param node_ismoving
	 */
	public final void setNode_IsMoving(java.lang.String node_ismoving)
	{
		setNode_IsMoving(getContext(), node_ismoving);
	}

	/**
	 * Set value of Node_IsMoving
	 * @param context
	 * @param node_ismoving
	 */
	public final void setNode_IsMoving(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String node_ismoving)
	{
		getMendixObject().setValue(context, MemberNames.Node_IsMoving.toString(), node_ismoving);
	}

	/**
	 * @return value of Configured
	 */
	public final java.lang.Boolean getConfigured()
	{
		return getConfigured(getContext());
	}

	/**
	 * @param context
	 * @return value of Configured
	 */
	public final java.lang.Boolean getConfigured(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Configured.toString());
	}

	/**
	 * Set value of Configured
	 * @param configured
	 */
	public final void setConfigured(java.lang.Boolean configured)
	{
		setConfigured(getContext(), configured);
	}

	/**
	 * Set value of Configured
	 * @param context
	 * @param configured
	 */
	public final void setConfigured(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean configured)
	{
		getMendixObject().setValue(context, MemberNames.Configured.toString(), configured);
	}

	/**
	 * @return value of GatePLC_MonitoredItem
	 */
	public final java.util.List<opcuaclientmx.proxies.MonitoredItem> getGatePLC_MonitoredItem() throws com.mendix.core.CoreException
	{
		return getGatePLC_MonitoredItem(getContext());
	}

	/**
	 * @param context
	 * @return value of GatePLC_MonitoredItem
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<opcuaclientmx.proxies.MonitoredItem> getGatePLC_MonitoredItem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<opcuaclientmx.proxies.MonitoredItem> result = new java.util.ArrayList<opcuaclientmx.proxies.MonitoredItem>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.GatePLC_MonitoredItem.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(opcuaclientmx.proxies.MonitoredItem.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of GatePLC_MonitoredItem
	 * @param gateplc_monitoreditem
	 */
	public final void setGatePLC_MonitoredItem(java.util.List<opcuaclientmx.proxies.MonitoredItem> gateplc_monitoreditem)
	{
		setGatePLC_MonitoredItem(getContext(), gateplc_monitoreditem);
	}

	/**
	 * Set value of GatePLC_MonitoredItem
	 * @param context
	 * @param gateplc_monitoreditem
	 */
	public final void setGatePLC_MonitoredItem(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<opcuaclientmx.proxies.MonitoredItem> gateplc_monitoreditem)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (opcuaclientmx.proxies.MonitoredItem proxyObject : gateplc_monitoreditem)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.GatePLC_MonitoredItem.toString(), identifiers);
	}

	/**
	 * @return value of GatePLC_OpcUaServerCfg
	 */
	public final opcuaclientmx.proxies.OpcUaServerCfg getGatePLC_OpcUaServerCfg() throws com.mendix.core.CoreException
	{
		return getGatePLC_OpcUaServerCfg(getContext());
	}

	/**
	 * @param context
	 * @return value of GatePLC_OpcUaServerCfg
	 */
	public final opcuaclientmx.proxies.OpcUaServerCfg getGatePLC_OpcUaServerCfg(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		opcuaclientmx.proxies.OpcUaServerCfg result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GatePLC_OpcUaServerCfg.toString());
		if (identifier != null)
			result = opcuaclientmx.proxies.OpcUaServerCfg.load(context, identifier);
		return result;
	}

	/**
	 * Set value of GatePLC_OpcUaServerCfg
	 * @param gateplc_opcuaservercfg
	 */
	public final void setGatePLC_OpcUaServerCfg(opcuaclientmx.proxies.OpcUaServerCfg gateplc_opcuaservercfg)
	{
		setGatePLC_OpcUaServerCfg(getContext(), gateplc_opcuaservercfg);
	}

	/**
	 * Set value of GatePLC_OpcUaServerCfg
	 * @param context
	 * @param gateplc_opcuaservercfg
	 */
	public final void setGatePLC_OpcUaServerCfg(com.mendix.systemwideinterfaces.core.IContext context, opcuaclientmx.proxies.OpcUaServerCfg gateplc_opcuaservercfg)
	{
		if (gateplc_opcuaservercfg == null)
			getMendixObject().setValue(context, MemberNames.GatePLC_OpcUaServerCfg.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.GatePLC_OpcUaServerCfg.toString(), gateplc_opcuaservercfg.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return gatePLCMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final implementation_2_onegenericevent.proxies.GatePLC that = (implementation_2_onegenericevent.proxies.GatePLC) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Implementation_2_OneGenericEvent.GatePLC";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
